### ISSUE TITLE
Admin media should be added via a mixin so it doesn't break other admin extensions

### ISSUE THREAD

**Issue by andybak** [lukasvinclav/django-admin-numeric-filter#10]
Maybe similar to how GeoModelAdmin works:

    @property
    def media(self):
        "Injects OpenLayers JavaScript into the admin."
        return super().media + Media(js=[self.openlayers_url] + self.extra_js)

In the short term you should mention in the install docs that the current recommended way to do things will break other stuff.

**Comment by lukasvinclav** [comment]
Hi,

thanks for valuable feedback. Needed change has been added into source code and the fix will be available in the next release.

https://github.com/lukasvinclav/django-admin-numeric-filter/commit/09931c98e08cca18a5e9585bf3dc58caef340ac3
