### ISSUE TITLE
Latest code not on PyPi

### ISSUE THREAD

**Issue by dmwyatt** [lukasvinclav/django-admin-numeric-filter#15]
Any chance we can get the latest code released to PyPi?

**Comment by CelestialGuru** [comment]
I too would like the latest code on PyPi. I don't like git urls in my requirements.txt file if I can avoid it...

**Comment by michaelschem** [comment]
@dmwyatt @CelestialGuru has anyone forked this? I think this project has been abandoned.

**Comment by lukasvinclav** [comment]
hey @michaelschem today I updated the pypi version

**Comment by michaelschem** [comment]
@lukasvinclav thanks so much! If you want help administering this happy to help!
