### ISSUE TITLE
Filter not shown with Django JET

### ISSUE THREAD

**Issue by coder0028** [lukasvinclav/django-admin-numeric-filter#20]
@lukasvinclav filter widget not displayed when used with Django JET theme package. Is it not supported yet ?

**Comment by homarques** [comment]
Have you found a workaround?

**Comment by MAbdurrehman1** [comment]
I am facing the same issue.
Do we have any updates on this?

**Comment by lukasvinclav** [comment]
To be honest, I don't have any experience with Django JET admin theme. But feel free to investigate the issue and create the PR if it is needed.
