### ISSUE TITLE
I have error ImportError

### ISSUE THREAD

**Issue by Konark-Web** [lukasvinclav/django-admin-numeric-filter#23]
Hello. I want to use your number range filter, but I got error:
`ImportError: cannot import name ‘ugettext_lazy’ from ‘django.utils.translation’`

**Comment by alihoseiny** [comment]
Same problem. The code in the repository is correct. But the published package code is old and incorrect for Django 4.

**Comment by peter-stuart-turner** [comment]
same also hit this

**Comment by hoanghust** [comment]
For Django 4:
File "...env/lib/python3.9/site-packages/admin_numeric_filter/forms.py", line 2, in <module>
    from django.utils.translation import ugettext_lazy as _
You can fix above error by change "ugettext_lazy" to "gettext_lazy" in "...env/lib/python3.9/site-packages/admin_numeric_filter/forms.py".
