### ISSUE TITLE
The text of the filter doesn't translate 

### ISSUE THREAD

**Issue by Dusheba** [lukasvinclav/django-admin-numeric-filter#24]
I use LANGUAGE_CODE setup in Django settings (USE_I18N and USE_L10N are also = True) and I want my admin panel to be translated into Russian language. Everything except the filters from this lib has been translated. 
![image](https://user-images.githubusercontent.com/74534204/161641188-b6d5c547-c6ae-46ee-a320-bd200031cf04.png)

**Comment by akiyoko** [comment]
This seems to be a mistake in the message written in the template.
If you modify it as follows, it will work correctly.

```diff
diff --git a/admin_numeric_filter/templates/admin/filter_numeric_range.html b/admin_numeric_filter/templates/admin/filter_numeric_range.html
index 9c70b1c..254e63e 100644
--- a/admin_numeric_filter/templates/admin/filter_numeric_range.html
+++ b/admin_numeric_filter/templates/admin/filter_numeric_range.html
@@ -8,7 +8,7 @@
             {% endif %}
         {% endfor %}

-        <h3>{% blocktrans with filter_title=title %}By {{ filter_title }}{% endblocktrans %}</h3>
+        <h3>{% blocktrans with filter_title=title %} By {{ filter_title }} {% endblocktrans %}</h3>

         <div class="admin-numeric-filter-wrapper-group">
             {{ choice.form.as_p }}
```

**Comment by lukasvinclav** [comment]
Hey @akiyoko, would you mind to create a PR for this? Thanks

**Comment by akiyoko** [comment]
@lukasvinclav, I created the pull request. Please check it out.
