### ISSUE TITLE
Missing wNumb javascript mapping causes collectstatic crash

### ISSUE THREAD

**Issue by jurrian** [lukasvinclav/django-admin-numeric-filter#30]
Since Django 4.0, collectstatic post-processes source maps found in js files. See this [django ticket](https://code.djangoproject.com/ticket/32383).
The file wNumb.min.js contains this:

```//# sourceMappingURL=wNumb.min.js.map```

However the map does not exist. So either generate the map or remove this line.
Currently this prevents everyone using `ManifestStaticFilesStorage` from running collectstatic cause it crashes.

**Comment by lukasvinclav** [comment]
hey, thanks for report. Would you mind to create a PR? I will merge it and create new release.

**Comment by jurrian** [comment]
Sure, shall I remove the sourceMappingURL line?

**Comment by lukasvinclav** [comment]
Yep

**Comment by lukasvinclav** [comment]
Thanks for PR. New package published.
